a = input('Digite Algo: ')
print('O tipo primitivo desse valor é: ', type(a))
print('Só tem espaços? ', a.isspace())
print('É um numero?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('É alfanumerico?', a.isalnum())
print('Está em letras maiúsculas?', a.isupper())
print('Éstá em letras minúsculas?', a.islower())
print('Éstá capitalizadas?', a.istitle())
